name: 📻 Auto DJ Inmortal gratis 24/7

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */5 * * *'

jobs:
  transmitir:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Clonar las canciones de GitHub (Versión Moderna)
      uses: actions/checkout@v4

    - name: 🐧 Instalar Liquidsoap en el Robot
      run: |
        sudo apt-get update
        sudo apt-get install -y liquidsoap

    - name: 🎶 ¡Prender la radio y transmitir!
      env:
        STREAM_HOST: ${{ secrets.STREAM_HOST }}
        STREAM_PORT: ${{ secrets.STREAM_PORT }}
        STREAM_PASSWORD: ${{ secrets.STREAM_PASSWORD }}
        STREAM_MOUNT: ${{ secrets.STREAM_MOUNT }}
      run: |
        liquidsoap /home/runner/work/${{ github.event.repository.name }}/${{ github.event.repository.name }}/radio.liq
